[package]
name = "runjs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
deno_ast = { version = "=0.40.0", features = ["transpiling"] }
deno_core = "0.316.0"
tokio = { version = "1.41.0", features = ["full"] }
ureq = "2.10.1"
